import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@xefi/xui/style.css';
import './globals.css';
import ThemeProvider from '../providers/ThemProvider';
import QueryProvider from '../providers/QueryProvidre';
import NavbarCompnent from '@/components/NavbarCompnent';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={inter.className} suppressHydrationWarning>
				<ThemeProvider
					attribute='class'
					defaultTheme='light'
					enableSystem
					disableTransitionOnChange>
					<QueryProvider>
						{/* <AppsLayoutComponent>{children}</AppsLayoutComponent> */}
						{/* <NavbarComponent /> */}
						<NavbarCompnent />
						<div className="w-3/4 mx-auto" >

							{children}
						</div>
					</QueryProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}